spring:
  application:
    name: tasker
  datasource:
    url: jdbc:postgresql://localhost:5432/tasker
    username: postgres
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
app:
  security:
    jwt:
      secret: ${JWT_SECRET:ZwKk5xPn7LP1gJS7tCBv2GwG8bKFNPsQyi+MDYm8iqtWOnioExb5hSITPLs1aeKu7KjYajOCYVN6Y6ZA/M5nFA==}
      issuer: "tasker-app"
      access-token-ttl-min: 60
      refresh-token-ttl-days: 7

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html